version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088" # Map host port 8088 to container port 8088
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8088
      - ConnectionStrings__DefaultConnection=Data Source=database,1433;Initial Catalog=CarManagment;User ID=sa;Password=carManagment12345*;TrustServerCertificate=True;
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "carManagment12345*"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
